### ISSUE TITLE
Error when $npx elm-pages dev

### ISSUE THREAD

**Issue by rolojf** [dillonkearns/elm-pages-3-alpha-starter#2]
When issued that command, or `$npm run start` The first thing showing is the following error:

> Failed to start port-data-source watcher Error: Build failed with 2 errors:
> error: Could not resolve "./port-data-source"
> /home/a/mmep3/elm-pages/generator/src/dev-server.js:159:65: ERROR: [plugin: example] Cannot read properties of undefined (reading 'outputs')
>     at failureErrorWithLog (/home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:1605:15)
>     at /home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:1251:28
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   errors: [
>     {
>       detail: undefined,
>       location: null,
>       notes: [],
>       pluginName: '',
>       text: 'Could not resolve "./port-data-source"'
>     },
>     {
>       pluginName: 'example',
>       text: "Cannot read properties of undefined (reading 'outputs')",
>       location: [Object],
>       notes: [Array],
>       detail: TypeError: Cannot read properties of undefined (reading 'outputs')
>           at /home/a/mmep3/elm-pages/generator/src/dev-server.js:159:66
>           at /home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:1042:21
>           at runOnEndCallbacks (/home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:1047:11)
>           at buildResponseToResult (/home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:1249:7)
>           at /home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:1358:14
>           at /home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:668:9
>           at handleIncomingPacket (/home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:765:9)
>           at Socket.readFromStdout (/home/a/mmep3/elm-pages/node_modules/esbuild/lib/main.js:635:7)
>           at Socket.emit (node:events:527:28)
>           at addChunk (node:internal/streams/readable:324:12)
>     }
>   ],
>   warnings: []
> }

The elm page is built ok and rendered on clicking on the link.

**Comment by dillonkearns** [comment]
Yes, this is on my todo list. It's just reporting that the project doesn't have a port-data-source file defined so it doesn't include it. This is the file that is used when you use `DataSource.Port`s. Thanks for the issue, I'll close this since I'm tracking it separately 🙏

**Comment by dillonkearns** [comment]
And to clarify, the action on my todo list is to differentiate between a missing port-data-source file (which is not a problem and can either be silent or a warning), vs. a port-data-source file that has errors (which should give an error). It's a bit difficult to distinguish the two, so that's an item on my todo list. For now it just prints whatever error directly instead of trying to present it in a nicer way.
