### ISSUE TITLE
Effect on Shared on OnPageChange message not performed 

### ISSUE THREAD

**Issue by rolojf** [dillonkearns/elm-pages-3-alpha-starter#5]
An effect, called from `Shared.elm` module update function with Message `OnPageChange` does not get performed.

The same effect performs ok when called from some where else. 

Looked at examples on the elm-pages repo and didn't find an effect being called on the `OnPageChage` message.  Only found `Effect.None`.

Maybe I am missing something.  But I spent quite some time `debug.logging`, checking out the console and the network tab. And I know it's and Alpha.  Maybe this is a bug then.

Regards,  Rolando

**Comment by rolojf** [comment]
I managed to reproduce this same behavior on a clean fresh install of this repo.

Saludos

**Comment by rolojf** [comment]
Checked again (September 17) on latest update of this repo. I believe the issue is still there.

**Effect is not getting called OnPageChange.**

For example:
An Effect defined as:
`GetTheTime (Time.Posix -> msg)` and performing as:  `GetTheTime toMsg -> Task.perform (toMsg >> fromPageMsg) Time.now `

And on `Shared.elm` update case branches as:
```
        OnPageChange _ ->
            ( { model | pageChanges = model.pageChanges + 1 }
            , Effect.GetTheTime TimeNow 
            )

        GetTimeButtonPressed ->
            ( model, Effect.GetTheTime TimeNow )

        TimeNow time ->
            ( { model | time = Just time }
            , Effect.none
            )
```

With this, I can not get the time from the last OnPageChanged on my model. But the model.pageChanges does increment and  if I press the GetTimeButton the Effect does it's job and I get the time on my model.

Hope I made myself more clear now.

Regards,

**Comment by rolojf** [comment]
I usually work on firfox. This time I checked that on Chromium, this same situation still happens.

Also, as an another way to confirm that this is happening, I added a counter as follows:

```
OnPageChange _ ->
            ( { model | pageChanges = model.pageChanges + 1 }
            , Effect.GetTheTime TimeNow
            )
```

And the update function does get called with the OnPageChange message and the counter adds one every time I change the page, as expected.  But still, the effect is not being performed.

Regards,

**Comment by dillonkearns** [comment]
Hello @rolojf, thanks for reporting the issue! I believe I may have fixed this in the latest beta package in this commit: https://github.com/dillonkearns/elm-pages-v3-beta/commit/98736e0a395d368e84f3f407c1cd82a0c919126c#diff-9829b0ad92d940bec18206754f647376616c51701f1dd65b5a10fafa755b7e4cR606.

If you're up for trying it out in the latest beta, you can try it with this starter repo: https://github.com/dillonkearns/elm-pages-3-alpha-starter

I'd love to hear how it's going with the latest code there.

**Comment by rolojf** [comment]
Yup, this is fixed now. 

I am just using V2 functionality for now, even on this alpha version.  In a month or so, I think, I will have the time to start experimenting all the new exciting stuff that V3 brings to the table. Now elm-pages feels like a powerful  Leatherman multi tool. 

Thanks

**Comment by dillonkearns** [comment]
Great, thank you for checking, and thanks for your feedback!
